# =============================================================================
# PR Labeler Configuration
# Labels are applied based on files changed in the PR
# =============================================================================

# Package labels
api:
  - changed-files:
      - any-glob-to-any-file: 'packages/api/**/*'

admin-ui:
  - changed-files:
      - any-glob-to-any-file: 'packages/admin-ui/**/*'

database:
  - changed-files:
      - any-glob-to-any-file: 'packages/database/**/*'

core:
  - changed-files:
      - any-glob-to-any-file: 'packages/core/**/*'

sdk:
  - changed-files:
      - any-glob-to-any-file: 'packages/sdk/**/*'

stripe:
  - changed-files:
      - any-glob-to-any-file: 'packages/adapters/stripe/**/*'

# Type labels
documentation:
  - changed-files:
      - any-glob-to-any-file:
          - '**/*.md'
          - 'docs/**/*'
          - 'packages/web/**/*'

tests:
  - changed-files:
      - any-glob-to-any-file:
          - '**/*.test.ts'
          - '**/*.spec.ts'
          - '**/test/**/*'
          - '**/__tests__/**/*'

infrastructure:
  - changed-files:
      - any-glob-to-any-file:
          - 'Dockerfile*'
          - 'docker-compose*.yml'
          - '.github/**/*'
          - 'infrastructure/**/*'
          - '*.tf'

dependencies:
  - changed-files:
      - any-glob-to-any-file:
          - 'package.json'
          - 'yarn.lock'
          - '**/package.json'

migrations:
  - changed-files:
      - any-glob-to-any-file: 'packages/database/prisma/migrations/**/*'

config:
  - changed-files:
      - any-glob-to-any-file:
          - '*.config.*'
          - '.env*'
          - 'tsconfig*.json'
